### ISSUE TITLE
Can't load the world

### ISSUE THREAD

**Issue by SirioIlBe** [NFINIT-Development/Planetary#19]
i get this crash when i try to load my world:
https://paste.dimdev.org/ofiluqohid.mccrash
https://i.imgur.com/MaduZIc.png

**Comment by knoxhack** [comment]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/672

**Comment by SirioIlBe** [comment]
so what should i do?

**Comment by knoxhack** [comment]
Does this still happens in 1.1.6?

**Comment by SirioIlBe** [comment]
yes...i had to delete discord mod again
