### ISSUE TITLE
Laser base/drill missing osmium ore

### ISSUE THREAD

**Issue by SirioIlBe** [NFINIT-Development/Planetary#21]
the laser base/drill from industrial foregoing is missing the osmium ore.(don't know if there should be more .. i just noticed this one)
(plus: i think there are only vanilla dense ore in the world)
edit: i think platinum and nickel too.. i have the right lense for platinum but i never got it...even if the gui says that you can get it from the laser

**Comment by knoxhack** [comment]
I haven't found a way to add custom ores to the laser drill from that mod, if anyone find a way to do that let me know yo implement it

**Comment by SirioIlBe** [comment]
there is a folder called laser_drill_ores in the config folder...i think its that.

**Comment by knoxhack** [comment]
awesome, thanks

**Comment by knoxhack** [comment]
Fixed in 1.1.7
