### ISSUE TITLE
SpaceX Rocket Repair & GC Wrench

### ISSUE THREAD

**Issue by burshaz** [NFINIT-Development/Planetary#24]
Repairing the rocket stages does not require the wrench in the crafting grid or inventory.
Most recently tested in 1.1.6

Additionally when pulling the repaired rocket out of the grid a GC wrench is created (minus some durability)

![2020-01-30_15 26 44](https://user-images.githubusercontent.com/6723579/73578128-7afbab00-4444-11ea-8250-c82aae76636f.png)

**Comment by knoxhack** [comment]
Oh, now I understand.
I simply fix would be to add the wrench as a required item to craft along the damanged rocket part

**Comment by knoxhack** [comment]
Fixed in 1.1.7
