### ISSUE TITLE
Chapter 1 Meteor Chest Quest

### ISSUE THREAD

**Issue by blackout6vi6** [NFINIT-Development/Planetary#25]
There is a missing item that is part of the meteor chest quest in chapter 1. I am not able to progress to chapter 2. 
![Annotation 2020-02-01 122719](https://user-images.githubusercontent.com/48000830/73596198-3fb5b680-44ee-11ea-84ea-78a0b4671e5f.jpg)

**Comment by blackout6vi6** [comment]
Version 1.1.6 single player no server

**Comment by knoxhack** [comment]
Fixed in 1.1.7
