### ISSUE TITLE
Landing on Mars doesn't finish

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Planetary#27]
I tested this in Singleplayer:
- Build complete Falcon rocket on Overworld making sure all modules are fueled
- Launch and enter space
- Select Mars and hit Launch
- Screen switches to Mars and the Falcon capsule descends, then before reaching the ground landing thrusters start firing
- Capsule hits ground then sits there. No way to exit the capsule. A/S keys rotate the capsule.

The only way to continue is leaving to main menu, then when entering the game again you are at a high Y coordinate falling down to the surface without capsule. Died from fall damage, and a grave was normally created but I spawned more than 1000 blocks away, so no way to get there without oxygen equipment. 
I switched to Creative and went to my grave, besides the grave the capsule also was there.

(Version 1.17)

![image](https://user-images.githubusercontent.com/4916644/73827765-6f233680-4800-11ea-9bc5-63c44ddf556a.png)

**Comment by knoxhack** [comment]
When I try to replicate this with just Galacticraft and SpaceCraft X installed it doesn't happen, so it must be another mod in the pack causing it

**Comment by knoxhack** [comment]
This also seems to happen with the galacticraft rockets 🤔

**Comment by mtbrenner** [comment]
I'll make this limited pack myself tonight to see how it is supposed to work.

**Comment by ROMVoid95** [comment]
I have had nothing but issues the 2 times i used this mod while testing galacticraft addons for compatibility. 

does going to mars via the /dimensiontp give the same result?

**Comment by ROMVoid95** [comment]
i received the same error when i launched to space with the Falcon9 and clicked on earth to travel back. Interestingly enough, if you press spacebar again, you can fly around the world.

This is a issue with the mod itself. Unfortunately, since it's abandoned and not open source. i dont know if a fix exists.

**Comment by mtbrenner** [comment]
Made a pack with the same Galacticraft version as in Planetary (newest Galacticraft version together with SpacecraftX crashes at title screen) and exploded once, and safely landed twice with using SPACE key to slowdown the descent like you have to do it with the Galacticraft lunar lander. I then tested again in Planetary and successtully landed using the same method (slowing down with space key). Maybe the problem is incorrect handling of the crashing case?

**Comment by ROMVoid95** [comment]
yes more than likely, i base this off the last time the mod was updated, and when the changes to Galacticaft's rocket entry changed. Biggest indicator was the countdown timer on launch staying at 1

which should NOT happen. as the 20 seconds is used by gc to handle chunk gen for possible destinations.

**Comment by knoxhack** [comment]
Clean log: https://raw.githubusercontent.com/NFINIT-Development/Planetary/master/log1.txt

**Comment by knoxhack** [comment]
log with EvilNotchLib-SNAPSHOT-103.jar and dungeontweaks-1.2.6.4.jar disabled: https://raw.githubusercontent.com/NFINIT-Development/Planetary/master/log2.txt

**Comment by knoxhack** [comment]
apparently disabling Evilnotch fixes this bug, gonna go ahead and report it to them

**Comment by knoxhack** [comment]
Fixed in 1.1.8 https://www.curseforge.com/minecraft/modpacks/planetary/files/2878539
