### ISSUE TITLE
My issues so far.

### ISSUE THREAD

**Issue by boxz0r** [NFINIT-Development/Planetary#29]
I havent had a single successful landing on any planet. Can't exit the pod, have to log out and back in. When logging back in you spawn mid air, making it a real clusterf**k every time. Sometimes ive spawned underground when logging back in. pod is always lost.

Heavy-Duty plate - Tier 10 cant be made. Nothing happens when I put Compressed dark iron in the compressor.
No recipe for Tier 10 rocket fins. So the tier 10 rocket cannot be made.
Nasa workbench has no recipe-

**Comment by br1c** [comment]
I've created an unofficial patch that patches every game breaking or major bug in the modpack. The problem with exiting the pod was already patched by Knoxhack, but I fixed the problems with the missing recipes. Here's the download:
[Planetary.zip](https://github.com/NFINIT-Development/Planetary/files/4894540/Planetary.zip)

**Comment by kphoenix137** [comment]
The quest related problems have all been corrected and well be released in the next update.
