### ISSUE TITLE
SpaceX Rocket Repair & GC Wrench the 2nd

### ISSUE THREAD

**Issue by Aringarosa** [NFINIT-Development/Planetary#30]
Hi there,

i live in Germany so sry for my bad spelling.

The Issue #24 solved the Repair at all. Now the Recipe need a fully repaird GC Wrench to be valid. 
Here is a Screenshot:

![2020-02-09_15h01_44](https://user-images.githubusercontent.com/5900536/74103553-41febd00-4b4d-11ea-9354-0ac25e1ec791.png)

Second Problem is the Recipe duplicate the Rocket Parts. The damaged one stays in the crafting Grid an do not delete.

Greetings  Ringo

**Comment by knoxhack** [comment]
Thanks for reporting it

**Comment by knoxhack** [comment]
Fixed in 1.1.8 https://www.curseforge.com/minecraft/modpacks/planetary/files/2878539
