### ISSUE TITLE
Lithium Dust - Missing Recipe?

### ISSUE THREAD

**Issue by Aringarosa** [NFINIT-Development/Planetary#31]
Hello,

another Problem is somewhat annoying. Maybe it is Intended?

Lithium Ingot can only obtainable by smelting Lithium Ore directly in a Furnace. If processed, in may case in trough the Mod Mekanism, into Lithium Dust, the Dust can not Processed into Ingots.

Greetings Ringo

**Comment by knoxhack** [comment]
Thanks, fixed in 1.1.8 https://www.curseforge.com/minecraft/modpacks/planetary/files/2878539
