### ISSUE TITLE
Discord-1.12.2-1.0.7.jar - WorldCrash on Load in SMP

### ISSUE THREAD

**Issue by Aringarosa** [NFINIT-Development/Planetary#33]
Hello,

some Serious Issue i have encountered ist the Discord-Mod. It causes a world to crash on Load (SMP tested) if a "Digital Miner" from Mekanism or "Farmer" from Industrial Forgoing  (examples) was placed and active on World quit. The core problem is the fake player event from divers Machines that interact with Block in the world.

The Crash is known at the Mekanism Tracker as  Issue 5641 and solved by remove the Discord Mod.

Suggested Solution: Remove Discord Mod

Today after Work i will do a Testworld with only necessary mods to check the link between them.

Greetings Ringo

**Comment by knoxhack** [comment]
Should be good to report it to the discord mod dev too

**Comment by Aringarosa** [comment]
Testsetup:
Mc 1.12.2
forge-14.23.5.2847

Mods:
Mekanism-1.12.2-9.8.3.390
Discord-1.12.2-1.0.7

ToDo:
Creative World
Build digital Miner + creative Power source
Set filter to Stone
Start the Digital Miner
Save / exit World
Load world and:


> java.lang.NullPointerException: Ticking block entity
> 	at ca.teamdman.discordintegration.PresenceEventHandler.onHarvest(PresenceEventHandler.java:165)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_PresenceEventHandler_onHarvest_BreakEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at mekanism.common.tile.TileEntityDigitalMiner.canMine(TileEntityDigitalMiner.java:366)
> 	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:230)
> 	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)
> 	at net.minecraft.world.World.func_72939_s(World.java:1838)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Unknown Source)

Same with Industrial Foregoing

Setup a planter / gatherer and some power, in my chase Mekanism und viola:

java.lang.NullPointerException: Ticking block entity
	at ca.teamdman.discordintegration.PresenceEventHandler.onHarvest(PresenceEventHandler.java:165)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_PresenceEventHandler_onHarvest_BreakEvent.invoke(.dynamic)
	at 

> net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at com.buuz135.industrial.utils.BlockUtils.canBlockBeBroken(BlockUtils.java:99)
> 	at com.buuz135.industrial.tile.agriculture.CropRecolectorTile.work(CropRecolectorTile.java:109)
> 	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:112)
> 	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)
> 	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:120)
> 	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
> 	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:991)
> 	at net.minecraft.world.World.func_72939_s(World.java:1838)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Unknown Source)


Remove Discord.jar and all works fine.
I will do a report to the Discord Dev Team.

**Comment by TeamDman** [comment]
https://www.curseforge.com/minecraft/mc-mods/discord/files/2879457
This should have a fix, please let me know if it does or doesn't work for you!
Thanks for reporting this.

**Comment by Aringarosa** [comment]
The new Version runs fine. Testsetup and Planetary-world loads as usual.
