### ISSUE TITLE
Kepler 22b - Dungeon Chests

### ISSUE THREAD

**Issue by Aringarosa** [NFINIT-Development/Planetary#35]
Hello,

i have visited four out of five Dungeons on Kepler 22b. All Chests are most likely complete empty. If one out of ten have some Items it is, i guss, the lootingtable of the Dungeons from home on earth. One chest in a whole Dungeon has the Dungeon special loot, i guss it is the rare chest.

Current Version: 1.1.8

Greetings Ringo

Edith says:

I looked into the .cfg of the Dungeons. I am not a Pack Dev but for example the kepler22bandriod.cfg has no entry for the matteroverdrive android parts. And as they are no loot drop they are unobtainable.

**Comment by mtbrenner** [comment]
I also did some testing on SP. I was wondering why only 2 types of dungeons show up on the kepler22b surface (android and military). I manually spawned some dungeons with /dldspawn and found that the 3 other dungeon types are generated, but only underground, and as Aringarosa says, chests are empty. I looked in the debug log and found this exception:

[dldungeons.txt](https://github.com/NFINIT-Development/Planetary/files/4190291/dldungeons.txt)

This is probably causing the empty chests and preventing building the entrance(s) on the surface:[DLDUNGEONS] Danger!  Failed to finalize a dungeon after building!

I tested replacing the chestfile reference in the 3 problematic dungeons with kepler22bmilitary.cfg so these dungeons would spawn the known good military chests and now those dungeons spawned WITH the correct surface entrances and military-loot filled chests.

I don't know what loot item causes the problem, but fixing the specialchest config files should fix this issue.

**Comment by mtbrenner** [comment]
Example coords on Kepler22b for a "failed" dungeon: X: -1410, Y: 34, Z: -1548

**Comment by Swantsy** [comment]
yup, experiencing the same problem

**Comment by SilverBeamx** [comment]
The problem is very simple. After digging through the DLDungeons code, with the log provided by mtbrenner, the dungeon generation crashes due to the fact that, apart from the Military and Android dungeons, the other types are missing level 2 and 3 loot to their loot table. As such, if a level 2 or 3 chest is rolled, the dungeon generator crashes outright.

**Comment by br1c** [comment]
I've created an unofficial patch that patches every game breaking or major bug in the modpack. It completely fixes the dungeons and loot tables too. Here's the download:
[Planetary.zip](https://github.com/NFINIT-Development/Planetary/files/4894538/Planetary.zip)

**Comment by kphoenix137** [comment]
All of these problems have been fixed for the next update.
