### ISSUE TITLE
Unable to build Tier 10 rocket

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Planetary#37]
Tier 10 rocket requires the NASA workbench which is unavailable.
Tier 10 rocket requires dark iron which is unavailable (seems to be made from Eris Dark Iron Ore)
Launching the rocket requires a Tier3 rocket launch pad which doesn't have a recipe.

**Comment by br1c** [comment]
I've created an unofficial patch that patches every game breaking or major bug in the modpack. It allows you to completely finish the modpack with no problems. Here's the download:
[Planetary.zip](https://github.com/NFINIT-Development/Planetary/files/4894535/Planetary.zip)

**Comment by kphoenix137** [comment]
This issue will be fixed in the next update of Planetary.
