### ISSUE TITLE
Unable to finish quest Kepler 22b Space Station

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Planetary#38]
I built a Kepler22b space station but the quest didn't complete, probably because the quest requires you to visit a static dimension.

**Comment by br1c** [comment]
I've created an unofficial patch that patches every game breaking or major bug in the modpack. It allows for the final quest to be completed as well. Here's the download:
[Planetary.zip](https://github.com/NFINIT-Development/Planetary/files/4894532/Planetary.zip)

**Comment by kphoenix137** [comment]
This is all fixed in the upcoming update of Planetary.
