### ISSUE TITLE
Unable to find grass or gather seeds from XL Food mod

### ISSUE THREAD

**Issue by NovaLynxie** [NFINIT-Development/Planetary#39]
I've noticed that XL Food mod grass no longer spawns in the world. It used to spawn in failed mob dungeons, even if it was just one or two grass patches. Now I cannot find any. Because of this I cannot find any of the seeds to grow said crops. 
According to JEI this is the only grass that has a chance to drop these seeds, but so far I have not found a single bit of them anywhere. Traveled very far out too.
![image](https://user-images.githubusercontent.com/21307676/74613754-eada8880-5108-11ea-9521-a951386b82dc.png)
Any ideas why it no longer spawns anymore in the world, or am I just very unlucky?

**Comment by kphoenix137** [comment]
The expansion of more crops isn't something that is vital to the theme and progression of the modpack, so this likely will not see any changes in the future.
