### ISSUE TITLE
Unable to download modpack

### ISSUE THREAD

**Issue by movsesian258** [NFINIT-Development/Planetary#40]
Unable to download modpack , when i try to download modpack twitch says : An object reference does not indicate an instance of an object.
![Снимок](https://user-images.githubusercontent.com/61289787/74963992-12449480-542c-11ea-9241-0b025763337e.PNG)

game version - unknown
last update - unknown

**Comment by kphoenix137** [comment]
This is a Twitch issue, not a modpack issue. Unfortunately we cannot help with this.
