### ISSUE TITLE
Rescue Mission in chapter 3 not unlocking

### ISSUE THREAD

**Issue by Swantsy** [NFINIT-Development/Planetary#42]
even though everything else possible in the chapter has been done, it won't unlock the rescue mission, and as such we are unable to continue. co-op playthrough.

![image](https://user-images.githubusercontent.com/19387179/75097805-2b298300-55af-11ea-8e30-5a703f1335f6.png)

**Comment by vistajames** [comment]
I had the same issue and I finally moved in to chapter four to hammer out questions. Not sure what quest unlocked the rescue mission but after completing a few in chapter 4 it unlocked. I've never seen quests locked by quests in a further ahead section.
