### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by zLenb98** [NFINIT-Development/Planetary#49]
Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 316898 in database. Aborting installation

When i try to download the modpack

**Comment by br1c** [comment]
If you are still having this problem, delete all remnants of Planetary from your Twitch/Instances folder, then attempt a reinstall. If that doesn't work, reinstall your Twitch client then attempt to reinstall.

**Comment by kphoenix137** [comment]
This problem is a problem with Twitch and not the modpack itself.
