### ISSUE TITLE
failed mob does not spawn

### ISSUE THREAD

**Issue by Super8M** [NFINIT-Development/Planetary#53]
i don't now why but in my world the dungeons spawner of failed animals doesn't work, but the other spawn in the other dungeons works normaly.
There is something that i can do ? like commands or something else

best regards M. G.

**Comment by br1c** [comment]
Are you still having this issue? You should attempt to mine them with silk touch or use a Cardboard Box to move them, and see if they work then. I am not certain if they require light and grass to spawn on, but it's worth a shot. Alternatively, if you place a large patch of grass on the surface of your world and leave your base, then return, normal animals will begin to spawn on the grass, so long as you are out of range.

**Comment by kphoenix137** [comment]
Unable to replicate issue. In the current version of Planetery, there appears to be no issue with Failed Mobs spawning via their spawners. Please note that Failed Mobs need Grass Blocks to be able to spawn, which are naturally found in Failed Labs anyway.
