### ISSUE TITLE
Kepler 22b missing loot and some chest are empity

### ISSUE THREAD

**Issue by Dreaming-Codes** [NFINIT-Development/Planetary#55]
I fixed it https://drive.google.com/file/d/1uueZW_7WMm43BMvu56hNiQEMUCBb5C5x/view?usp=sharing

**Comment by knoxhack** [comment]
Hey, thanks a lot :)
I'll be testing it and implementing it on next update

**Comment by br1c** [comment]
I've created an unofficial patch that patches every game breaking or major bug in the modpack, and I included your fix. You did manage to fix the android part problem, but the labs were still having problems generating entrances and populating many of the chests. Here is the download:
[Planetary.zip](https://github.com/NFINIT-Development/Planetary/files/4894526/Planetary.zip)
