### ISSUE TITLE
Kepler22b woods crafting table recipe not working

### ISSUE THREAD

**Issue by Hynisel** [NFINIT-Development/Planetary#56]
Hi, i would like to report what is probably a bug,there is problem with the crafting recipe of the crafting table using Kepler22b wooden planks, it seems that both crafting table and pressure plate have the same crafting recipe,the correct recipe to create pressure plate is actually creating sticks, please refer to the screenshots below, this prevent the creation of the crafting table using Kepler22b woods.

Client version:1.1.10

![2020-04-25_17 24 20](https://user-images.githubusercontent.com/53999494/80283907-6bc28b80-871b-11ea-8281-3a9455f1754f.png)

![2020-04-25_17 26 47](https://user-images.githubusercontent.com/53999494/80283925-83017900-871b-11ea-9d6c-6f8316bbf507.png)

![2020-04-25_17 35 11](https://user-images.githubusercontent.com/53999494/80283930-8dbc0e00-871b-11ea-872a-6960c9c34b0b.png)

**Comment by br1c** [comment]
Hi, I've attached a fix for this problem. It modifies all the corresponding crafting recipes.
-The Kepler 22b Planks will now be used in the same arrangement as vanilla wood types to make Sticks (Kepler 22b variants), Crafting Tables, and Oak Pressure Plates. Extract this to your Instances directory.
[Planetary.zip](https://github.com/NFINIT-Development/Planetary/files/4893254/Planetary.zip)

**Comment by br1c** [comment]
I've created an unofficial patch that patches every game breaking or major bug in the modpack, including your problem with the planks. I'll upload it here.
[Planetary.zip](https://github.com/NFINIT-Development/Planetary/files/4894516/Planetary.zip)

**Comment by kphoenix137** [comment]
Full fix for this issue coming in the next update.
