### ISSUE TITLE
[BUG] This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 231951

### ISSUE THREAD

**Issue by thecloakedevil** [NFINIT-Development/Planetary#60]
### ---Bug Report---
**(PLEASE DON'T DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[After it checks the files and attempts to download and copy the files from twitch launcher, it gives this error.]

### Steps to Reproduce Issue
1. [Go to Twitch, minecraft mods]
2. [Go to browse modpacks, search planetary]
3. [Click install and wait for error]

**Crash log/Log (if applicable):** [Pastebin URL Here]

**Screenshots (if applicable):** [Screenshots here]

**Version of Planetary using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.1.10]

**Where did this bug happen:** [in the twitch launcher when trying to install the modpack]

### Additional Information
[I tried the latest version, 1.2.0, and it deleted files as soon as it created with various errors each time I tried, i.e. missing addon planetary or missing addon spacecraft x or another addon id: ######]

**Comment by kphoenix137** [comment]
Do not use version 1.1.10 as it's not able to be completed. We will need additional information otherwise we won't be able to fix the issue.

**Comment by knoxhack** [comment]
This was a problem with twitch servers
