### ISSUE TITLE
[Request] Add lapis lazuli to some DML mob to automate PPC.

### ISSUE THREAD

**Issue by riacob** [NFINIT-Development/Planetary#65]
I suggest adding lapis lazuli as a possible obtainable resource from a mob in deep mob learning, which would make automation of pulsating polymer clay much easier.

**Comment by SquidPig1** [comment]
just use industrial forgoing to get a laser and mine for it that way. then use one of the furni to turn it into lapis. works very well

**Comment by riacob** [comment]
Thanks for replying, but it has been quite a bit and I am no longer playing this.
Thinking about it, should probably have closed this a long time ago lol.
