### ISSUE TITLE
Cant enter corpses[BUG]

### ISSUE THREAD

**Issue by XavierIdk** [NFINIT-Development/Planetary#78]
### ---Bug Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
no
### Description of Issue
Corpses cant be opened

### Steps to Reproduce Issue
1. [die]
2. [go to death location]
3. [try to open the corpse]

**Crash log/Log (if applicable):** [Pastebin URL Here]

**Screenshots (if applicable):** [Screenshots here]
![2022-08-06_21 53 43](https://user-images.githubusercontent.com/110742763/183264304-276237ec-fc5b-471a-9a8e-49825fab3a72.png)

**Version of Planetary using (PLEASE DONT USE 'Latest' OR 'Newest'):** [Version here]
Version 1.4
**Where did this bug happen:** [Text here]
at my base
### Additional Information
my friend died due to lack of oxygen and when he tried to open his corpse it wouldnt let him

![2022-08-06_21 53 43](https://user-images.githubusercontent.com/110742763/183264304-276237ec-fc5b-471a-9a8e-49825fab3a72.png)

**Comment by knoxhack** [comment]
fixed in 1.4.2
